### ISSUE TITLE
Course Content Roadmap

### ISSUE THREAD

**Issue by mateiidavid** [Ben-Woolley/java-for-beginners#8]
#### Course content:

1. [x] Intro, installing, set-up
2. [x] Basic building blocks
3. [x] Less basic building blocks
4. [x] Classes & Methods
5. ~[ ] Input/output~
6. ~[ ]  Inheritance and composition~
7. ~[ ] Testing~
8. ~[ ] Bonus/extra content/spillover~

---

**Comment by mateiidavid** [comment]
Update: crossed 5 through 8 for now
